FROM jupyter/all-spark-notebook

RUN pip3 install psycopg2-binary pandas numpy








#Deriving the latest base image
#FROM python:latest


#Labels as key value pair
#LABEL Maintainer="roushan.me17"


# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
#WORKDIR /usr/app/src

#to COPY the remote file at working directory in container
#COPY BI_mini_project.ipynb ./
# Now the structure looks like this '/usr/app/src/test.py'


#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

#CMD [ "jupyter/all-spark-notebook", "./BI_mini_project.ipynb"]